# baseURL = 'https:blog.justinchen928.com/'
languageCode = 'zh-TW'
title = '分而治之'
subtitle = 'Breaking down complex problems into manageable pieces.'
theme = 'beautifulhugo'
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# analytics
googleAnalytics = "G-MT7HR3N3JQ"

[Params]
  homeTitle = "分而治之" # Set a different text for the header on the home page
  subtitle = 'Breaking down complex problems into manageable pieces.'
  mainSections = ["post","posts"]
  logo = "https://lh3.googleusercontent.com/a/AGNmyxblZR66us2Lf-12avON_Y-rlMmDfb9wxzFcqir_RQ=s96-c-rg-br100"
  favicon = "img/favicon.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
#   Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
#   name = "Some Person"
#   website = "yourwebsite.com"
#   email = "youremail@domain.com"
#   facebook = "username"
  github = "justinchen928"
#   gitlab = "username"
#   bitbucket = "username"
#   twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"
#   codepen = "username"
#   mastodon = "url"
#   kaggle = "username"
#   weibo = "username"
#   slack = "username"
#   discord = "invite code (https://discord.gg/XXXXXXX)"
#   strava = "userid"

[[menu.main]]
    name = "@CHIH-YU"
    url = "about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3